Feature/issue assigned
gedankenessen/goose-frontend pull request #50
Opened 2021-04-10 13:59 UTC by Namo2

Issue Assigned (#29) ist fertig

2021-04-11 12:45 UTC, Namo2 commented
Für den PR werde ich noch das unsubscriben einbauen

2021-04-12 20:25 UTC, Namo2 commented
Die änderungen für das Unsubscribe sind jetzt in der Branch.
Bitte reviewn.

Zusätzlich noch 2 Screenshots:
=> Hinzufügen
![grafik](https://user-images.githubusercontent.com/48796374/114457069-e5c67b80-9bdd-11eb-99ea-7f7d6bd737ff.png)

=> Ansicht
![grafik](https://user-images.githubusercontent.com/48796374/114457166-0393e080-9bde-11eb-9422-e1a45e1e1eb2.png)

2021-04-12 22:30 UTC, marlonschlosshauer requested changes

2021-04-12 22:30 UTC, marlonschlosshauer commented on src/app/issue/issue-assigned/issue-assigned.component.ts
> +  // TODO: Evtl die auswahl Liste filtern nach Usern welche noch nicht assigned wurden?
Yes, das bräuchte es noch 👍

2021-04-13 16:31 UTC, Namo2 commented
Hab die Filterung nun eingebaut. Hier ein Beispiel:
![grafik](https://user-images.githubusercontent.com/48796374/114587947-7062b580-9c86-11eb-9bbd-23d21512d106.png)

2021-04-13 17:04 UTC, marlonschlosshauer approved these changes
Bin kein riesiger Fan davon die "filteredSelectionList" per Hand zu updaten, aber die change detection von Angular ist 💩 
Gute Arbeit 👍

2021-04-13 17:21 UTC, Namo2 commented
> 
> 
> Bin kein Fan davon die "filteredSelectionList" per Hand zu updaten, aber die change detection von Angular ist 💩
> Gute Arbeit 👍

Du kannst mir ja gerne später mal zeigen wie du es implementiert hättest. Vllt kann ich es ja dann noch ändern

2021-04-13 17:24 UTC, marlonschlosshauer commented
> > Bin kein Fan davon die "filteredSelectionList" per Hand zu updaten, aber die change detection von Angular ist 💩
> > Gute Arbeit 👍
> 
> Du kannst mir ja gerne später mal zeigen wie du es implementiert hättest. Vllt kann ich es ja dann noch ändern

Ne kein Bock, hab selber keinen Plan wie man den shit triggert. Manchmal macht er es, manchmal nicht. Wenn du mal lachen möchtest: Hau ein console.log in ne Funktion die von einem UI Element aufgerufen wird. Kann sein das Angular die gesamte Komponente jede Sekunde neu baut ... für immer 🙃

2021-04-14 07:57 UTC, BenjaminKuerten approved these changes

2021-04-14 09:52 UTC, merged