PR Änderungen implementiert
gedankenessen/goose-frontend pull request #76
Opened 2021-04-26 11:42 UTC by mschwer1

2021-04-26 12:01 UTC, Namo2 approved these changes

2021-04-26 16:28 UTC, WhiroWhat approved these changes

2021-04-26 18:19 UTC, marlonschlosshauer requested changes

2021-04-26 18:19 UTC, marlonschlosshauer commented on src/app/issue/summary/summary.component.ts
>    httpOptions = {
Wird das noch gebraucht?

2021-04-26 18:19 UTC, marlonschlosshauer commented on src/app/issue/summary/summary.component.ts
> +    this.expectedTime = 1;
Würde das auf 0 machen das der Validator auch greifen kann. Könntest du auch bei der deklaration direkt schreiben
```js
expetedTime: number = 0;
```

2021-04-26 18:58 UTC, WhiroWhat requested changes

2021-04-26 18:58 UTC, WhiroWhat commented on src/app/issue/summary/summary.component.ts
>    ): Observable<any> {
Die Funktion gibt nichts zurück.

2021-04-26 22:02 UTC, Namo2 reviewed
Sieht meiner Meinung nach gut aus.

Würde nur evtl in GetRessources das
`data => ...` in eine Zeile schreiben und die zwei unnötigen leerzeilen entfernen.

Evtl noch bei den Funktionen welche nichts returnen 
`: void` angeben

2021-04-27 08:36 UTC, marlonschlosshauer approved these changes

2021-04-27 08:36 UTC, merged