Feature/issue component vs2
gedankenessen/goose-frontend pull request #78
Opened 2021-04-28 09:57 UTC by sfuerder

Alle Features von VS2 für IssueComponent wurden implementiert

closes #52

2021-04-28 12:27 UTC, mschwer1 approved these changes

2021-04-28 12:52 UTC, Namo2 requested changes
Bei Zeile 107-120 könnte man das Ergebniss des subscribes Pipen und dann über tap() speichern

```js
this.IssueRequirementService.createRequirement(this.issueId, requirement).pipe(
      tap(data => {
        this.requirements = [...this.requirements, data];
        this.newRequirement = '';
      })
   );
```
Allerdings bin ich mir dann nicht sicher wie man dann das Error Handling behandelt.
Bis jetzt lassen wir das nur über den BaseService regeln, was ja auch reichen würde.

Würde das ganze etwas kürzer halten

2021-04-28 12:52 UTC, Namo2 commented on src/app/issue/issue/issue.component.ts
>      );
Sollte das wirklich ein zwei Zeiler sein.

Fände einen Einzeiler ohne Klammern schöner

2021-04-28 14:50 UTC, WhiroWhat approved these changes

2021-04-29 07:00 UTC, marlonschlosshauer approved these changes
Top wie immer 👍 
Sind ein paar unsued Variablen/Services (``issuePredecessors``) und Kommentare drin. Hau die das nächste mal raus. 
Wenn die Errors so verwendet werden wie hier (mit dem Modal) können wir das gerne machen.

2021-04-29 07:02 UTC, marlonschlosshauer commented on src/app/issue/issue/issue.component.ts
>      );
> @marlonschlosshauer wie würdest du das sehen, wenn wir diese Error Ausgaben behalten wollen würden?

So hat das echten Nutzen, also auf jeden beibehalten 👍

2021-04-29 09:53 UTC, Namo2 approved these changes

2021-04-29 10:18 UTC, sfuerder commented
> Top wie immer 👍
> Sind ein paar unsued Variablen/Services (`issuePredecessors`) und Kommentare drin. Hau die das nächste mal raus.
> Wenn die Errors so verwendet werden wie hier (mit dem Modal) können wir das gerne machen.

Diese unused variablen werden wieder benötigt, sobald die Vorgänger und Untertickets angezeigt werden. Das hatte ich schon beim ersten mal hinzugefügt gehabt, nur da war das backend dort noch nicht soweit. Deshalb hatte ich ein Teil aaskommentiert und die Variablen wohl vergessen.
Macht ja keinen Sinn, dass ich das wieder komplett lösche oder?

2021-04-29 10:21 UTC, sfuerder commented on src/app/issue/issue/issue.component.ts
>      );
> Bei Zeile 107-120 könnte man das Ergebniss des subscribes Pipen und dann über tap() speichern

Macht das einen großen Unterschied? Habe Pepe und Tap tatsächlich noch nie benutz. Denke aber, dass das was ich genutzt habe nicht so einen großen Unterschied macht oder?

2021-04-29 10:25 UTC, Namo2 commented on src/app/issue/issue/issue.component.ts
>      );
Habs vorhin dann doch approved. Weil ich keine Ahnung habe ob du mit tap dann noch dein Error Handling machen könntest

2021-04-29 10:28 UTC, sfuerder commented on src/app/issue/issue/issue.component.ts
>      );
Das andere war ein Einzeiler, bis die Autoformatierung das geändert hat. Werde das noch ändern

2021-04-29 10:48 UTC, Namo2 commented on src/app/issue/issue/issue.component.ts
>      );
Das ist mittlerweile eh egal. Haben ja jetzt auch die Autoformatierung für die Commits

2021-04-29 10:53 UTC, marlonschlosshauer commented
> > Top wie immer 👍
> > Sind ein paar unsued Variablen/Services (`issuePredecessors`) und Kommentare drin. Hau die das nächste mal raus.
> > Wenn die Errors so verwendet werden wie hier (mit dem Modal) können wir das gerne machen.
> 
> Diese unused variablen werden wieder benötigt, sobald die Vorgänger und Untertickets angezeigt werden. Das hatte ich schon beim ersten mal hinzugefügt gehabt, nur da war das backend dort noch nicht soweit. Deshalb hatte ich ein Teil aaskommentiert und die Variablen wohl vergessen.
> Macht ja keinen Sinn, dass ich das wieder komplett lösche oder?

Ich hab mir gedacht man könnte das über die getPredecessor Parameter bei getIssue gleich mit holen. Gäb es da einen Unterschied zu dem holen über die Services? 

Im großen und ganzen auch egal, kannst mergen 👍

2021-04-29 12:23 UTC, merged