Feature/zugriffsrechte projekt dashboard
gedankenessen/goose-frontend pull request #79
Opened 2021-04-28 12:39 UTC by Namo2

Hey,

habe von meinem AP #68 die Anforderung T16 fertiggestellt.
(Projekt Erstellen Button ist nur noch für den Firmen Account Sichtbar)

Zudem wegen T84 wird die QickAction für die Projekteinstellungen nurnoch für User angezeigt, 
welche in diesem Projekt schreibrechte besitzen.

Nebenbei habe ich auch eine Sortierung der Tabelle anhand des Kunden (Nach-)namens eingefügt.

2021-04-28 14:04 UTC, BenjaminKuerten approved these changes

2021-04-28 14:57 UTC, WhiroWhat requested changes

2021-04-28 14:57 UTC, WhiroWhat commented on src/app/project/dashboard/dashboard.component.html
> +      [hidden]="!this.isCompanyAccount()"
*ngIf="!this.isCompanyAccount()" wäre besser als [hidden]

2021-04-28 14:57 UTC, WhiroWhat commented on src/app/project/dashboard/dashboard.component.html
> +            [hidden]="!project.hasWritePermission"
*ngIf

2021-04-28 16:14 UTC, Namo2 commented
Habs mal geändert. Sieht wirklich besser aus. Vorallem, da ich die Funktionen nicht negieren muss

2021-04-28 16:31 UTC, WhiroWhat commented
https://www.angularjswiki.com/angular/difference-between-ngif-and-hidden-or-displaynone-in-angular/
ist auch besser für performance

2021-04-28 16:31 UTC, WhiroWhat approved these changes

2021-04-29 06:40 UTC, mschwer1 approved these changes

2021-04-29 10:09 UTC, sfuerder approved these changes

2021-04-29 10:27 UTC, merged