Feature/customer dashboard
gedankenessen/goose-frontend pull request #80
Opened 2021-04-28 15:16 UTC by Luk-T

resolves #28 

Fügt das Customer-Dashboard hinzu. Der Quickactions-Button funktioniert allerdings noch nicht.
Feedback ist erwünscht, hab eine Weile kein Angular mehr geschrieben.

2021-04-28 17:26 UTC, Namo2 requested changes

2021-04-28 17:26 UTC, Namo2 commented on src/app/customer/customer-dashboard/customer-dashboard.component.ts
> +    this.getAllResources(companyId).subscribe();
Hier müsste der Subscription Wrapper benutzt werden

```js
this.subscribe(this.getAllResources(companyId));
```

2021-04-28 18:16 UTC, Luk-T commented on src/app/customer/customer-dashboard/customer-dashboard.component.ts
> +    this.getAllResources(companyId).subscribe();
Habs hinzugefügt, danke für den Hinweis

2021-04-28 18:37 UTC, Namo2 approved these changes

2021-04-29 06:43 UTC, mschwer1 approved these changes

2021-04-29 10:12 UTC, sfuerder approved these changes

2021-04-29 13:53 UTC, WhiroWhat approved these changes

2021-04-29 14:37 UTC, merged