Feature/issue settings
gedankenessen/goose-frontend pull request #87
Opened 2021-04-29 23:07 UTC by BenjaminKuerten

2021-04-30 08:09 UTC, sfuerder approved these changes

2021-04-30 20:23 UTC, marlonschlosshauer requested changes

2021-04-30 20:23 UTC, marlonschlosshauer commented on src/app/issue/settings/settings.component.ts
> +      }
Könnte man abkürzen:
```suggestion
      this.issue.issueDetail.visibility = (this.visibleInput === 'extern');
```

2021-04-30 20:23 UTC, marlonschlosshauer commented on src/app/issue/settings/settings.component.html
>        <nz-option nzValue="extern" nzLabel="Extern"></nz-option>
Hier könntest du als nzValue ``true`` für extern machen (statt dem String), dann hast du es in der .ts einfacher.

2021-04-30 20:23 UTC, marlonschlosshauer commented on src/app/issue/settings/settings.component.ts
> +      id: '',
Lieber id ``undefined`` lassen, wenn es sowieso als default "Überprüft" setzen wird.

2021-04-30 20:23 UTC, marlonschlosshauer commented on src/app/issue/settings/settings.component.ts
> +    return listOfDocuments;
Könnte man auch in einer Zeile schreiben:
```suggestion
    return IssueRelevantDocuments.map(i => i.name);
```

2021-04-30 20:23 UTC, marlonschlosshauer commented on src/app/issue/settings/settings.component.ts
> +  }
Gibt immer ``[]`` zurück

2021-04-30 20:23 UTC, marlonschlosshauer commented on src/app/issue/settings/settings.component.ts
> +        (error) => {
Hau die in der ganzen Datei raus

2021-04-30 22:00 UTC, BenjaminKuerten commented
@marlonschlosshauer Die IssueDetails sind noch Altlasten, die sind doppelt und können raus. Du gibst mir nochmal bescheid wann der Grundlagen-Programmierkurs ist, dass ich richtig kommentieren lerne und 3 Zeile Code spare.

2021-04-30 22:48 UTC, WhiroWhat requested changes

2021-04-30 22:48 UTC, WhiroWhat commented on src/app/issue/settings/settings.component.html
>                [hidden]="documentEditId === data.id"
*ngIf statt hidden

2021-04-30 22:48 UTC, WhiroWhat commented on src/app/issue/settings/settings.component.html
>                [hidden]="documentEditId !== data.id"
*ngIf

2021-05-01 09:38 UTC, marlonschlosshauer commented
> Du gibst mir nochmal bescheid wann der Grundlagen-Programmierkurs ist, dass ich richtig kommentieren lerne und 3 Zeile Code spare

Ich kanns dir erklären wenn du möchtest ¯\\\_(ツ)\_\/¯

2021-05-01 13:55 UTC, merged